// Who a post is written for. Unlike the textbooks, whose reading levels come out
// of graph.json, the blog spans "explain this to a friend with no maths" through
// to research-adjacent notes — and which one a post is turns out to be the thing
// a reader most wants to filter on, so it is authored per post.
export type BlogLevel = 'general' | 'undergrad' | 'graduate';

export const LEVEL_LABEL: Record<BlogLevel, string> = {
  general: 'General audience',
  undergrad: 'Undergraduate',
  graduate: 'Graduate',
};

// Chip order: easiest first, so the row reads as a ramp.
export const LEVEL_ORDER: BlogLevel[] = ['general', 'undergrad', 'graduate'];

export interface BlogTopic {
  key: string;
  label: string;
  blurb: string;
}

// A post as authored in blog-posts.ts, before the PDF's own metadata is merged in.
export interface BlogEntry {
  name: string;
  desc: string;
  link: string;
  topic: string;        // primary topic key — decides the chip it counts toward
  alsoTopics?: string[]; // secondary topics the post also answers to
  level: BlogLevel;
}

// A post as rendered: the authored entry plus what gen-blog-manifest.js read out
// of the PDF. The metadata fields are optional because a post whose PDF has not
// been compiled yet should degrade to a card without a date, not vanish.
export interface BlogPost extends BlogEntry {
  file: string;           // PDF basename — the manifest key
  topicLabel: string;
  alsoLabels: string[];   // display labels for alsoTopics, resolved once here
  levelLabel: string;
  updated?: string;       // ISO date of the last compile
  pages?: number;
  readingMinutes?: number;
}

// One entry per PDF in the manifest generated by scripts/gen-blog-manifest.js.
export interface BlogPdfMeta {
  pages: number | null;
  updated: string | null;
  readingMinutes: number | null;
}
export type BlogManifest = Record<string, BlogPdfMeta>;
